/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useProgress } from '@react-three/drei'
import MeshTowerMaterial from '../materials/MeshTowerMaterial'
import { Vector2 } from 'three'
import MeshDustMaterial from '../materials/MeshDustMaterial'
import gsap from 'gsap'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'

export default function EnergyTower( props ) 
{

  const tl = gsap.timeline()

  const progress = useProgress()

  const beamRef = useRef()
  const dustRef = useRef()

  const { nodes } = useGLTF('./models/tower.glb')

  useFrame( ( state, delta ) =>
  {
    if( progress.progress === 100 )
    {
      tl.to( dustRef.current.scale, {
        x: 1,
        y: 1,
        z: 1,
        duration: 0.8,
      })
      tl.to( beamRef.current.scale, {
        x: 1,
        y: 1,
        z: 1,
        duration: 1.2,
      }, '<')
    }
  })

  return (
    <group {...props} dispose={null}>

      <group ref={ beamRef } scale={ 0 }>
        <mesh
          geometry={nodes.Beam.geometry}
          position={[0, 7.25, 0]}
          scale={[1.3, 1, 1.3]}
        >
          <MeshTowerMaterial
              colorFront='#ABFBFF'
              colorBack='#00C6D1'
              skew={ true }
              skewAmount={ new Vector2( 0.0, 3 )}
              tile={ true }
              movementDirection={ new Vector2( 0.7, 0.4 ) }
              noise={ false }
              frontColorIntensity={ 1.2 }
              rimLighting={ true }
              rimDensity={ 1.7 }
              darken={true}
              darkenAmt={ 0.7 }
          />
      </mesh>

        <mesh
          geometry={nodes.Voronoi.geometry}
          position={[0, 7.25, 0]}
          scale={[1.68, 1, 1.68]}
        >
          <MeshTowerMaterial
              colorFront='#022028'
              movementDirection={ new Vector2( 0.0, 0.5 ) }
              tileAmount={ new Vector2( 3, 1 ) }
              skewAmount={ new Vector2( 0.0, 0.3 ) }
              clip={ true }
              tile={ true }
              skew={ true }
          />
      </mesh>

        <mesh
          geometry={nodes.Fresnel.geometry}
          position={[0, 7.25, 0]}
          scale={[1.568, 1, 1.568]}
        >
          <MeshTowerMaterial
              colorFront='#ABFBFF'
              colorBack='#ABFBFF'
              movementDirection={ new Vector2( 0.7, 0.5 )}
              tileAmount={ new Vector2( 3, 3 )}
              skewAmount={ new Vector2( 0.0, 0.5 ) }
              skew={ true }
              clip={ true }
              tile={ true }
              clipThreshold={ 0.6 }
              frontColorIntensity={ 1.1 }
              backColorIntensity={ 1.4 }
              backColored={ false }
          />
      </mesh>
    </group>

    <group ref={ dustRef } scale={ 0 }>
      <mesh
          geometry={nodes.Dust1.geometry}
          material={nodes.Dust1.material}
          position={[0, 1, 0]}
          scale={[2, 1, 2]}
        >
            <MeshDustMaterial 
                panOffset={ new Vector2( 1, 0.0 ) }
                colorIntensity={ 1.5 }
            />
        </mesh>

        <mesh
          geometry={nodes.Dust2.geometry}
          material={nodes.Dust2.material}
          position={[0, 1, 0]}
          scale={[2.7, 1, 2.7]}
        >
            <MeshDustMaterial
              color1='#022028' 
              color2='#022028'
              panOffset={ new Vector2( 0.8, 0.0 ) }
            />
        </mesh>
      </group>

    </group>
  )
}

useGLTF.preload('./models/tower.glb')